import Head from "next/head";
import dynamic from "next/dynamic";
import Link from "next/link";
import axios from "axios";
const Image = dynamic(() => import('antd').then(module => module.Image), {
  ssr: false
})

export async function getServerSideProps() {
  const { data } = await axios.get(
    `http://localhost:7777/products`
  );
  return { props: { data } };
}


// export async function getStaticProps() {
//   const res = await fetch('http://localhost:7777/products')
//   const repo = await res.json()
//   return { props: { repo } }
// }

  // export async function getServerSideProps() {
  //   const res = await fetch('http://localhost:7777/products')
  //   const repo = await res.json()
  //   return { props: { repo } }
  // }




export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>All products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="case">
          <div className="text">
            <p className="act">Pixel</p>
            <p>VGN</p>
            <p>Logitech Superlight 2</p>
            <p>Интересное</p>
            <p>Logitech Valentins Day</p>
          </div>
          <div className="wrapper">
            {data.map((el) => {
              return(
                <>
                    <Link href={`/products/${el.id}`}>
                      <div className="card">
                        <img src={el.img} alt="" />
                        <h1>{el.userId}</h1><br />
                        <p>{el.title}</p><br />
                        <b>{el.price} so'm</b><br /><br />
                        <button>В корзину</button>
                      </div>
                  </Link>
                </>
              )
            })}
          </div>
        </div>
      </header>
    </>
  );
}
